name       : bottom
version    : 0.4.7
release    : 1
source     :
    - https://github.com/ClementTsang/bottom/archive/0.4.7.tar.gz : 6194357517080cd76b21850a6d4547eb9c95bd2019d41e2866c80d6858e7ec87
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm
