name       : bottom
version    : 0.9.1
release    : 16
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.9.1.tar.gz : 15136784ba4783c994bbfc1fe978ccf47360b2f2aa14ce37f8d5f93871ec9d57
    - https://github.com/ClementTsang/bottom/releases/download/0.9.1/completion.tar.gz : 7bec6df57733028c57c5e80c807ed8c8f5b03fca7622cde55dd65a7971f8510c
    - https://github.com/ClementTsang/bottom/releases/download/0.9.1/manpage.tar.gz : 04a7b918c96693aefe3a5a6f54040323dabd06ab509254480016807da6a4e581
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
setup      : |
    cp $sources/completion.tar.gz .
    cp $sources/manpage.tar.gz .

    tar xf completion.tar.gz
    tar xf manpage.tar.gz
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm

    # Completions
    install -Dm00644 btm.bash $installdir/usr/share/bash-completion/completions/btm
    install -Dm00644 _btm $installdir/usr/share/zsh/site-functions/_btm
    install -Dm00644 btm.fish $installdir/usr/share/fish/vendor_completions.d/btm.fish

    # Manpages
    install -Dm00644 btm.1.gz $installdir/usr/share/man/man1/btm.1.gz
