name       : bottom
version    : 0.8.0
release    : 15
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.8.0.tar.gz : 0fe6a826d18570ab33b2af3b26ce28c61e3aa830abb2b622f2c3b81da802437a
    - https://github.com/ClementTsang/bottom/releases/download/0.8.0/completion.tar.gz : 0d66631e718caafab29b1daec00394342cc2460cb8f7c706bd4cc85143d73928
    - https://github.com/ClementTsang/bottom/releases/download/0.8.0/manpage.tar.gz : e0bcd05ddfd7e084a27d978f66688aeceba48a2acb5156f9c4dbb73a65e25a95
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
setup      : |
    cp $sources/completion.tar.gz .
    cp $sources/manpage.tar.gz .

    tar xf completion.tar.gz
    tar xf manpage.tar.gz
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm

    # Completions
    install -Dm00644 btm.bash $installdir/usr/share/bash-completion/completions/btm
    install -Dm00644 _btm $installdir/usr/share/zsh/site-functions/_btm
    install -Dm00644 btm.fish $installdir/usr/share/fish/vendor_completions.d/btm.fish

    # Manpages
    install -Dm00644 btm.1.gz $installdir/usr/share/man/man1/btm.1.gz
