name       : bottom
version    : 0.9.3
release    : 18
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.9.3.tar.gz : 53a1466c3d2ed8f38401e8929cf2da796e703e4d70339d215f855b2304c07f72
    - https://github.com/ClementTsang/bottom/releases/download/0.9.3/completion.tar.gz: 8def8f45031aa6303cf9e841eab2f9a38c7ac3d44bc82de62cf3e59e12903a6e
    - https://github.com/ClementTsang/bottom/releases/download/0.9.3/manpage.tar.gz: dc6c654e35acd7ed1585c432a809a2ac37746120ee949fd3badf9ff787f07113
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
setup      : |
    cp $sources/completion.tar.gz .
    cp $sources/manpage.tar.gz .

    tar xf completion.tar.gz
    tar xf manpage.tar.gz
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm

    # Completions
    install -Dm00644 btm.bash $installdir/usr/share/bash-completion/completions/btm
    install -Dm00644 _btm $installdir/usr/share/zsh/site-functions/_btm
    install -Dm00644 btm.fish $installdir/usr/share/fish/vendor_completions.d/btm.fish

    # Manpages
    install -Dm00644 btm.1.gz $installdir/usr/share/man/man1/btm.1.gz
