name       : bottom
version    : 0.6.6
release    : 11
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.6.6.tar.gz : 102932d73a5b053c81bb7d9a7a8af35a0da1f9f391a62a58ba5cd1702daf4429
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm
