name       : bottom
version    : 0.5.7
release    : 5
source     :
    - https://github.com/ClementTsang/bottom/archive/0.5.7.tar.gz : 49e01a2930d913dba2a1329389faddb4b3971a6b0c08f7482d2759475d5cc27c
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm
